# Basic
use_small_heuristics = "Max"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
# Misc
match_block_trailing_comma = true
use_field_init_shorthand = true

